<?php
// Export all players as browser-generated PDF (no external library)
// Includes new fields: blood_group and playing_years
// Accessible to admin only

session_start();
require_once __DIR__ . '/admin_auth.php';
require_once __DIR__ . '/player_repository.php';

// --- Authentication: Only admin allowed ---
if (empty($_SESSION['admin_auth_user'])) {
    header('Location: admin_login.php?next=player_export_pdf.php');
    exit;
}

// --- Get all players (ensure player_repository.get_all_players includes new fields) ---
$players = get_all_players();

// --- Prepare HTML table for PDF (browser print) ---
$fields = [
    'ID',
    'Full Name',
    'DOB',
    'Age Group',
    'Village',
    'Court',
    'Play Time',
    'Blood Group',       // NEW
    'Playing Years',     // NEW
    'Mobile',
    'Aadhaar',
    'Status',
    'Created At'
];

$now = date('d M Y, h:i A');
$count = count($players);

$html = '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Players Export PDF</title>
    <style>
        @media print {
            @page { margin: 18mm; }
            body { -webkit-print-color-adjust: exact; }
        }
        body { font-family: Arial, Helvetica, sans-serif; font-size: 11px; margin: 12px; color: #111827; }
        header { display:flex; align-items:center; justify-content:space-between; margin-bottom:8px; }
        .title { color: #2563eb; font-size:16px; font-weight:700; }
        .meta { font-size:12px; color:#6b7280; }
        table { width:100%; border-collapse: collapse; margin-top: 8px; table-layout: fixed; word-wrap:break-word; }
        th, td { border: 1px solid #e6eef8; padding: 6px 8px; vertical-align:top; text-align: left; }
        th { background: #f1f5f9; color: #0f172a; font-weight:700; font-size:11px; }
        tr:nth-child(even) td { background: #fbfdff; }
        td { font-size:11px; color:#0f172a; }
        .small { font-size:10px; color:#6b7280; }
        .center { text-align:center; }
        .nowrap { white-space:nowrap; }
        .footer { margin-top:10px; font-size:11px; color:#6b7280; }
    </style>
</head>
<body>
<header>
    <div>
        <div class="title">Latur Badminton League — Players Export</div>
        <div class="small">Exported on: ' . htmlspecialchars($now) . ' — Total records: ' . (int)$count . '</div>
    </div>
    <div class="meta small">Generated by LBL Admin Panel</div>
</header>

<table>
    <thead>
        <tr>';

foreach ($fields as $f) {
    $html .= '<th>' . htmlspecialchars($f) . '</th>';
}

$html .= '</tr>
    </thead>
    <tbody>';

foreach ($players as $p) {
    $html .= '<tr>';
    $html .= '<td class="nowrap">' . htmlspecialchars($p['id'] ?? '') . '</td>';
    $html .= '<td>' . htmlspecialchars($p['full_name'] ?? '') . '</td>';
    $html .= '<td class="nowrap">' . htmlspecialchars($p['dob'] ?? '') . '</td>';
    $html .= '<td>' . htmlspecialchars($p['age_group'] ?? '') . '</td>';
    $html .= '<td>' . htmlspecialchars($p['village'] ?? '') . '</td>';
    $html .= '<td>' . htmlspecialchars($p['court'] ?? '') . '</td>';
    $html .= '<td>' . htmlspecialchars($p['play_time'] ?? '') . '</td>';
    // NEW fields
    $html .= '<td class="center">' . htmlspecialchars($p['blood_group'] ?? '') . '</td>';
    $html .= '<td class="center">' . htmlspecialchars($p['playing_years'] ?? '') . '</td>';
    // remaining
    $html .= '<td class="nowrap">' . htmlspecialchars($p['mobile'] ?? '') . '</td>';
    $html .= '<td>' . htmlspecialchars($p['aadhaar'] ?? '') . '</td>';
    $html .= '<td class="nowrap">' . htmlspecialchars($p['status'] ?? '') . '</td>';
    $html .= '<td class="nowrap">' . htmlspecialchars($p['created_at'] ?? '') . '</td>';
    $html .= '</tr>';
}

$html .= '
    </tbody>
</table>

<div class="footer small">
    Note: This page opens the browser print dialog. Choose "Save as PDF" in the print dialog to save the export as a PDF file.
</div>

<script>
    // Auto-open print dialog and close window after a short delay (if opened in new tab)
    window.onload = function() {
        try {
            window.print();
            // Try to close the window after printing (may be blocked by browser)
            setTimeout(function(){ window.close(); }, 800);
        } catch (e) {}
    };
</script>
</body>
</html>';

echo $html;
exit;
?>